### ISSUE TITLE
Main technologies

### ISSUE THREAD

**Issue by MakisH** [DE-RSE/learn-and-teach#1]
Let's document here the discussion from today's meeting.

**Comment by jngrad** [comment]
Example of GitHub Action-generated static HTML using a minimal Jekyll template that I set up some time ago: https://github.com/espressomd/espressomd.github.io. Automatically deployed to: https://espressomd.github.io/

**Comment by CaptainSifff** [comment]
Looks good, and the input are markdown files that seem to be rendered nicely in plain github, too.

**Comment by MakisH** [comment]
For the [preCICE website](https://precice.org/), we also use GitHub pages with a simple template and all the content in Markdown.

- [Repository](https://github.com/precice/precice.github.io)
- [Documentation of the documentation](https://precice.org/docs-meta-overview.html)

But keep in mind we already have two different technologies and styles for the main de-RSE website and the chapters. We should not deviate too much, at least not stylistically.

**Comment by MakisH** [comment]
In #6, I just used Jekyll, building on top of the de-RSE chapters example.
