### ISSUE TITLE
Rename the repository to match URL?

### ISSUE THREAD

**Issue by MakisH** [DE-RSE/learn-and-teach#18]
In the `Settings > Pages` of this repository, I enabled publishing. If I understand the [GitHub documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) correctly, the repository name needs to have the same name as the intended relative URL. This means that the website is currently served at:

https://de-rse.org/survey_rse_training/ (Ignore the current style issues #17)

and not:

~~https://de-rse.org/teach-and-learn/~~
https://de-rse.org/learn-and-teach/

If we have settled with the name (summoning @CaptainSifff for that), I suggest that we now (and before it becomes widely known), rename the repository to `teach-and-learn`.

I anyway do not have permissions to do this. @jlinx you probably can. We then don't need to engage anyone else to make this public.

**Comment by CaptainSifff** [comment]
Let's rename it, I can do it. Of course all your links will get invalid.

**Comment by CaptainSifff** [comment]
Renaming now, @MakisH @jngrad

**Comment by MakisH** [comment]
@CaptainSifff I just realized that I (once again) mixed up `teach-and-learn` and `learn-and-teach`. This is definitely an easy-to-do-wrong name.

Can you please rename again to `learn-and-teach`?

**Comment by CaptainSifff** [comment]
Now it's learn-and-teach?
