### ISSUE TITLE
Place links to the page sources to ease the contribution process.

### ISSUE THREAD

**Issue by dokempf** [DE-RSE/learn-and-teach#21]
Like a "suggest edit" button that links to the file on GitHub. This would significantly lower the bar for crowd-sourced information.

**Comment by MakisH** [comment]
Hi @dokempf,

I have already placed such links at the end of the opening paragraph of each page:

https://github.com/DE-RSE/learn-and-teach/blob/61c7f69b4f71bafae3324fcd76b473ee85c0e846/_pages/learn.md#L11

Are you looking for something else?

**Comment by dokempf** [comment]
I had overread these links - my bad.
