### ISSUE TITLE
Current attempts at designing RSE curricula

### ISSUE THREAD

**Issue by MakisH** [DE-RSE/learn-and-teach#25]
In the teachingRSE meeting today, @jpthiele described a new group intending to design an RSE curricilum, while @jcohen02 mentioned that he knows of another similar attempt. We also have an appendix with such an example in https://github.com/CaptainSifff/paper_teaching-learning-RSE.

We could document these evolving works in the beginning of https://de-rse.org/learn-and-teach/

**Comment by CaptainSifff** [comment]
The current progress is visible here: https://github.com/the-teachingRSE-project/RSE-Masters
