### ISSUE TITLE
Add R-specific links to competencies?

### ISSUE THREAD

**Issue by Aariq** [DE-RSE/learn-and-teach#32]
I noticed there are many python-specific links in the [competencies page](http://de-rse.org/learn-and-teach/competencies/) and there are R counterparts to many of these (e.g. rOpenSci's package guide).  Given that R is a popular language in research (at least in life sciences), it might be nice to include some links.  I'm happy to add these after I get back from the conference.

**Comment by CaptainSifff** [comment]
Would be a great addition! Thank You!

**Comment by MakisH** [comment]
Closed via #34.
