### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MakisH** [DE-RSE/learn-and-teach#8]
Do we want a custom logo, like in the [chapters page](https://de-rse.org/chapter/), or just use de-RSE?

**Comment by CaptainSifff** [comment]
So, the simple, but actually appealing solution would be to start from the chapter Logo, but instead of putting the city in there, we could use "edu".

**Comment by CaptainSifff** [comment]
e.g. 
![edurse](https://github.com/DE-RSE/survey_rse_training/assets/3985335/58c52931-97d6-4b00-8150-a087f6cd9979)

**Comment by MakisH** [comment]
In relation to the discussion in https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/240, I was wondering how we want to present this page:

A. something Germany-specific?
B. something global, put together by de-RSE?
C. something completely global?

I guess we want something between B or C. In that case, the logo and domain name can remain `de-rse`, but we need to clarify that the content is put together by more than "just" the German RSE community.

**Comment by CaptainSifff** [comment]
so far we want  to put it under the domain of de-RSE, so this justifies a bit B.

**Comment by MakisH** [comment]
> e.g. ![edurse](https://private-user-images.githubusercontent.com/3985335/303800952-58c52931-97d6-4b00-8150-a087f6cd9979.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTAwNDEsIm5iZiI6MTcwODAwOTc0MSwicGF0aCI6Ii8zOTg1MzM1LzMwMzgwMDk1Mi01OGM1MjkzMS05N2Q2LTRiMDAtODE1MC1hMDg3ZjZjZDk5Nzkuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTUwOTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ1NTdlOTFkMjJhYjYwNTAyZGY5NGQ5MjFlMmMxMjQzMWU5Yjk1N2UxMGQxNThjYmRlNjY1ZmZlYjU3MDAzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gh5tHwzMySdqG7_ITUudF6S5lGOJMpO2aWSaxkmnUWs)



> e.g. ![edurse](https://private-user-images.githubusercontent.com/3985335/303800952-58c52931-97d6-4b00-8150-a087f6cd9979.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTAwNDEsIm5iZiI6MTcwODAwOTc0MSwicGF0aCI6Ii8zOTg1MzM1LzMwMzgwMDk1Mi01OGM1MjkzMS05N2Q2LTRiMDAtODE1MC1hMDg3ZjZjZDk5Nzkuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTUwOTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ1NTdlOTFkMjJhYjYwNTAyZGY5NGQ5MjFlMmMxMjQzMWU5Yjk1N2UxMGQxNThjYmRlNjY1ZmZlYjU3MDAzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gh5tHwzMySdqG7_ITUudF6S5lGOJMpO2aWSaxkmnUWs)

Is it just my impression, or is something off with the font?

**Comment by MakisH** [comment]
> > e.g. ![edurse](https://private-user-images.githubusercontent.com/3985335/303800952-58c52931-97d6-4b00-8150-a087f6cd9979.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTAwNDEsIm5iZiI6MTcwODAwOTc0MSwicGF0aCI6Ii8zOTg1MzM1LzMwMzgwMDk1Mi01OGM1MjkzMS05N2Q2LTRiMDAtODE1MC1hMDg3ZjZjZDk5Nzkuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTUwOTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ1NTdlOTFkMjJhYjYwNTAyZGY5NGQ5MjFlMmMxMjQzMWU5Yjk1N2UxMGQxNThjYmRlNjY1ZmZlYjU3MDAzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gh5tHwzMySdqG7_ITUudF6S5lGOJMpO2aWSaxkmnUWs)
> 
> Is it just my impression, or is something off with the font?

**Comment by CaptainSifff** [comment]
it's not the same font, only something close that I could quickly find.

**Comment by jngrad** [comment]
The SVG file doesn't seem to contain font family information. In Inkscape the "edu" text is displayed in a sans-serif font, while in Firefox it is displayed in a serif font. The "de" text is actually a path, so it always looks the same.

**Comment by MakisH** [comment]
Are there any common branding guidelines? I see all RSE communities using more or less the same graphics.

**Comment by CaptainSifff** [comment]
Kind of, the Logo I used is from the official de-RSE repositories.

**Comment by CaptainSifff** [comment]
https://github.com/DE-RSE/materials/tree/master/Vorlagen

**Comment by MakisH** [comment]
See also discussion in https://github.com/CaptainSifff/paper_teaching-learning-RSE/issues/240

**Comment by BeastyBlacksmith** [comment]
The specifaction of the logo is here: https://github.com/DE-RSE/logo-association#specifications
